In [3]:
import numpy as np
a=np.array([1,2,3])
print(a)

#걍 연습

[1 2 3]


In [8]:
b=np.array([3,4,5])
print(b)

[3 4 5]


In [10]:
c=np.array([1,2])

In [13]:
import numpy as np
print(a)
#벡터
b=np.array([[1,2,3],[4,5,6],[5,6,7]])#행렬 3*3
print(b)
c=np.array([[1,2],[2,3]]) #행렬 2*2
print(c)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [5 6 7]]
[[1 2]
 [2 3]]


In [16]:
x=np.zeros((3,2)) #0으로r 가득찬 3*2 행렬 (데이터 타입이 실수)
y=np.ones((3,4)) #1로 가득찬 3*4행렬
z=np.full((2,3),5) #5로 가득찬 2*3 행렬
print(x)
print(y)
print(z)


[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5 5 5]
 [5 5 5]]


In [25]:
#np.arrange(시작하는 값, 끝나는 값(디폴트=포함x),증가량(디폴트=1))
x=np.arange(0,10)
print(x)

#np.linspace(시작하는 값, 끝나는 값(디폴트=포함o),개수)
y=np.linspace(0,10,5)
print(y) #0부터 10까지 5개로 쪼개달라
y=np.linspace(0,10,5,endpoint=False)
#포함 안하는 경우
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0.   2.5  5.   7.5 10. ]
[0. 2. 4. 6. 8.]


In [28]:
#ndarray라는 형식의 변수
print(a.ndim) #차원, 차원이 1==벡터/2==행렬/
print(a.shape)
print(a.size) #스칼라가 몇 개 들어있나

1
(3,)
3


In [33]:
a=np.arange(0,10)
#10열짜리 벡터

b=a.reshape(2,5)
print(b)
#순서가 행부터 채웠음을 확인할 수 있음! 이게 중요

b=b.reshape(5,2)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [39]:
print(b[0,0]) #b행렬 0행 0열 출력
print()

b[2,1]=100
print(b)
print()

print(b[0,:]) 
print()

print(b[:,0])

0

[[  0   1]
 [  2   3]
 [  4 100]
 [  6   7]
 [  8   9]]

[0 1]

[0 2 4 6 8]


In [49]:
c=np.arange(0,12)
c=c.reshape(4,3)
print(c)

#c[:,:]는 행 전부다, 열 전부다
#c[시작지점:끝지점(포함x) , 시작지점:끝지점(포함x)]

#:=맨처음부터 맨 끝까지(포함)
#(시작지점):(끝지점, 포함x)


print()
print(c[0,1:])

print()
print(c[2,2:])

print()
print(c[:2,1])

print()
print(c[1:3,2:])

print()
print(c[-1,-1])
print(c[-2,-2])
print(c[-3,-2])

print()
print(c[1:-1,1:-1]) #두번쨰 행, 마지막행까지(포함x) 두번쨰 열부터 마지막열까지(포함x)
print(c[0:-2,2])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[1 2]

[8]

[1 4]

[[5]
 [8]]

11
7
4

[[4]
 [7]]
[2 5]
