<a href="https://colab.research.google.com/github/JoungMinJu/lab_study/blob/main/%EC%BC%80%EB%9D%BC%EC%8A%A4%EC%9D%98_simpleRNN%EA%B3%BC_LSTM_%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#임의의 입력 생성
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional

In [2]:
train_x=[[0.1,4.2,1.5,1.1,2.8],[1.0,3.1,2.5,0.7,1.1],[0.3,2.1,1.5,2.1,0.1],[2.2,1.4,0.5,0.9,1.1]]
print(np.shape(train_x))


#단어벡터의 차원은 5, 문장의 길이는 4
#=== 4번의 시점(timesteps) 가 존재하고 각 시점마다 5차원의 단어벡터가 입력으로 사용됨

#근데 RNN은 3D 텐서를 입력으로 받으니 배치크기 1을 추가해주기로 함.

(4, 5)


In [4]:
train_X = [[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]
train_X = np.array(train_X, dtype=np.float32)
print(train_X.shape)

(1, 4, 5)


simpleRNN 이해하기

return _sequences랑 return_state는 둘 다 기본값이 False


In [5]:
rnn = SimpleRNN(3)
# rnn = SimpleRNN(3, return_sequences=False, return_state=False)와 동일.
hidden_state = rnn(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))

#(1,3)크기의 텐서가 출력되는데 이는 마지막 시점의 은닉 상태
#return_sequences가 False면 SimpleRNN은 마지막 시점의 은닉상태만 출력한다.

hidden state : [[ 0.57115287  0.1982617  -0.7583325 ]], shape: (1, 3)


In [6]:
rnn = SimpleRNN(3, return_sequences=True)
hidden_states = rnn(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))

#모든 시점의 은닉상태를 출력

hidden states : [[[-0.9977512  -0.87980455  0.9997654 ]
  [-0.9988548  -0.9584737   0.7130008 ]
  [-0.9593922  -0.6364547   0.886513  ]
  [-0.93032634 -0.89243186 -0.07543024]]], shape: (1, 4, 3)


In [7]:
#return_state가 True면 마지막 시점의 은닉상태를 출력한다!! return_sequences와는 연관없이

rnn = SimpleRNN(3, return_sequences=True, return_state=True)
hidden_states, last_state = rnn(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))

hidden states : [[[ 0.999984   -0.6691228   0.9729525 ]
  [ 0.9999742  -0.9889648   0.5011535 ]
  [ 0.988636   -0.8049336   0.7405179 ]
  [ 0.99021876 -0.22474496  0.20397964]]], shape: (1, 4, 3)
last hidden state : [[ 0.99021876 -0.22474496  0.20397964]], shape: (1, 3)


LSTM 이해하기



In [8]:
lstm = LSTM(3, return_sequences=False, return_state=True)
hidden_state, last_state, last_cell_state = lstm(train_X)

#세개의 결과를 반환한다. 첫 번째 결과는 마지막 시점의 은닉상태
#return_state=True로 두면 마지막 시점의 은닉상태+++ 셀 상태까지 반환한다.

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))
print('last cell state : {}, shape: {}'.format(last_cell_state, last_cell_state.shape))



hidden state : [[-0.14705572 -0.62191796  0.20174392]], shape: (1, 3)
last hidden state : [[-0.14705572 -0.62191796  0.20174392]], shape: (1, 3)
last cell state : [[-0.25057414 -1.2320595   0.30725116]], shape: (1, 3)


In [9]:
lstm = LSTM(3, return_sequences=True, return_state=True)
hidden_states, last_hidden_state, last_cell_state = lstm(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_hidden_state, last_hidden_state.shape))
print('last cell state : {}, shape: {}'.format(last_cell_state, last_cell_state.shape))


hidden states : [[[ 0.0174267   0.17490199  0.40668735]
  [ 0.06974394  0.513146    0.2585876 ]
  [ 0.14396068  0.50222975  0.08823335]
  [ 0.27955917  0.4176643  -0.24818362]]], shape: (1, 4, 3)
last hidden state : [[ 0.27955917  0.4176643  -0.24818362]], shape: (1, 3)
last cell state : [[ 1.412346   1.7055229 -0.3999371]], shape: (1, 3)


Bidirectional(LSTM)이해하기
=양방향 LSTM

In [10]:
k_init = tf.keras.initializers.Constant(value=0.1)
b_init = tf.keras.initializers.Constant(value=0)
r_init = tf.keras.initializers.Constant(value=0.1)

#retrn_sequences가 True인 경우와 False인 경우에 대해 은닉상태의 값이 어떻게 바뀌는지 비교하기 위해
#출력되는 은닉상태의 값을 고정시켜줌



In [11]:
bilstm = Bidirectional(LSTM(3, return_sequences=False, return_state=True, \
                            kernel_initializer=k_init, bias_initializer=b_init, recurrent_initializer=r_init))
hidden_states, forward_h, forward_c, backward_h, backward_c = bilstm(train_X)

#return_state가 True인 경우에는 정방향 LSTM의 은닉상태와 셀상태, 역방향 LSTM의 은닉상태와 셀상태 4가지를 바환
#forward_h와 backward_h는 각각 정방향 LSTM의 마지막 시점의 은닉상태와, 역방향 LSTM의 첫번째 시점의 은닉상태 값이다. 
#그리고 이 두 값을 연결한 값이 hidden_states에 출력되는 값이다.

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
#return_sequences가 False인 경우 정방향 LSTM의 마지막 시점의 은닉 상태와 역방향 LSTM의 첫번째 시점의 은닉상태가 연결된 채 반환된다. 그래서(1,6)
print('forward state : {}, shape: {}'.format(forward_h, forward_h.shape))
print('backward state : {}, shape: {}'.format(backward_h, backward_h.shape))

hidden states : [[0.63031393 0.63031393 0.63031393 0.7038734  0.7038734  0.7038734 ]], shape: (1, 6)
forward state : [[0.63031393 0.63031393 0.63031393]], shape: (1, 3)
backward state : [[0.7038734 0.7038734 0.7038734]], shape: (1, 3)


In [12]:
bilstm = Bidirectional(LSTM(3, return_sequences=True, return_state=True, \
                            kernel_initializer=k_init, bias_initializer=b_init, recurrent_initializer=r_init))
hidden_states, forward_h, forward_c, backward_h, backward_c = bilstm(train_X)

#hidden_sates에서 모든 시점의 은닉상태가 출력된다. 

#역방향 LSTM의 첫 번째 시점의 은닉상태는 더이상 정방향 LSTM의 마지막 시점의 은닉상태와 연결되는 것이 아니라
#정방향 LSTM의 첫 번째 시점의 은닉상태와 연결된다.


In [13]:
print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('forward state : {}, shape: {}'.format(forward_h, forward_h.shape))
print('backward state : {}, shape: {}'.format(backward_h, backward_h.shape))

hidden states : [[[0.35906473 0.35906473 0.35906473 0.7038734  0.7038734  0.7038734 ]
  [0.5511133  0.5511133  0.5511133  0.58863586 0.58863586 0.58863586]
  [0.59115744 0.59115744 0.59115744 0.3951699  0.3951699  0.3951699 ]
  [0.63031393 0.63031393 0.63031393 0.21942244 0.21942244 0.21942244]]], shape: (1, 4, 6)
forward state : [[0.63031393 0.63031393 0.63031393]], shape: (1, 3)
backward state : [[0.7038734 0.7038734 0.7038734]], shape: (1, 3)
